### ISSUE TITLE
I have a question about running in MeshViewer.

### ISSUE THREAD

**Issue by star4s** [nero19960329/MeshViewer#1]
Hello, I am a beginner on QT. I need your help about MeshViewer program.
My Development environment is
VS2017
QT 5.12.1
VTK 8.0.1.

When I compile your MeshViewer program, I had a success message in the build.
However, it was not taken pop up any Qt windows for MeshViewer.
I tried to run the Qt Designer, I think there is no problem. 

I attach the log file. Can you check what problem is?

Thank you for your help.

**Comment by star4s** [comment]
Moc'ing mesh_processing.h...
  Uic'ing mesh_processing.ui...
  Moc'ing mesh_processing_interactor_style.h...
  Rcc'ing mesh_processing.qrc...
RCC : warning : No resources in 'C:\Users\user\Desktop\MeshViewer\MeshProcessing\mesh_processing.qrc'.
  
  color_table_handler.cpp
  moc_mesh_processing.cpp
  moc_mesh_processing_interactor_style.cpp
  icp_algorithm.cpp
  main.cpp
  mesh_operation.cpp
  mesh_processing.cpp
  mesh_processing_data_model.cpp
  mesh_processing_interactor_style.cpp
  mesh_segmenter.cpp
c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\utility(241): warning C4267: '초기화 중': 'size_t'에서 '_Ty2'(으)로 변환하면서 데이터가 손실될 수 있습니다.
          with
          [
              _Ty2=int
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xmemory0(881): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::pair<const _Kty,_Ty>::pair<int,unsigned __int64,0>(std::pair<int,unsigned __int64> &&) noexcept'에 대한 참조를 확인하십시오.
          with
          [
              _Kty=int,
              _Ty=int
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xmemory0(881): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::pair<const _Kty,_Ty>::pair<int,unsigned __int64,0>(std::pair<int,unsigned __int64> &&) noexcept'에 대한 참조를 확인하십시오.
          with
          [
              _Kty=int,
              _Ty=int
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\list(718): note: 컴파일 중인 함수 템플릿 인스턴스화 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,std::pair<int,unsigned __int64>>(_Alloc &,_Objty *const ,std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Alloc=std::allocator<std::_List_node<std::pair<const int,int>,std::_Default_allocator_traits<std::allocator<std::pair<const int,int>>>::void_pointer>>,
              _Ty=std::pair<const int,int>,
              _Objty=std::pair<const int,int>
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\list(716): note: 컴파일 중인 함수 템플릿 인스턴스화 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,std::pair<int,unsigned __int64>>(_Alloc &,_Objty *const ,std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Alloc=std::allocator<std::_List_node<std::pair<const int,int>,std::_Default_allocator_traits<std::allocator<std::pair<const int,int>>>::void_pointer>>,
              _Ty=std::pair<const int,int>,
              _Objty=std::pair<const int,int>
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\list(950): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *std::_List_buy<_Ty,_Alloc>::_Buynode<std::pair<int,unsigned __int64>>(std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Ty=std::pair<const int,int>,
              _Alloc=std::allocator<std::pair<const int,int>>
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\list(950): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *std::_List_buy<_Ty,_Alloc>::_Buynode<std::pair<int,unsigned __int64>>(std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer> *,std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Ty=std::pair<const int,int>,
              _Alloc=std::allocator<std::pair<const int,int>>
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\list(917): note: 컴파일 중인 함수 템플릿 인스턴스화 'void std::list<std::pair<const _Kty,_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>::_Insert<std::pair<int,unsigned __int64>>(std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>,std::_Iterator_base0>,std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Kty=int,
              _Ty=int
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\list(917): note: 컴파일 중인 함수 템플릿 인스턴스화 'void std::list<std::pair<const _Kty,_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>::_Insert<std::pair<int,unsigned __int64>>(std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const _Kty,_Ty>>>,std::_Iterator_base0>,std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Kty=int,
              _Ty=int
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xhash(300): note: 컴파일 중인 함수 템플릿 인스턴스화 'void std::list<std::pair<const _Kty,_Ty>,std::allocator<std::pair<const _Kty,_Ty>>>::emplace_front<std::pair<int,unsigned __int64>>(std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Kty=int,
              _Ty=int
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\unordered_map(304): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::_Hash<std::_Umap_traits<_Kty,int,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::emplace<std::pair<int,unsigned __int64>>(std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Ty=std::pair<const int,int>,
              _Kty=int,
              _Hasher=std::hash<int>,
              _Keyeq=std::equal_to<int>,
              _Alloc=std::allocator<std::pair<const int,int>>
          ]
  c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\unordered_map(304): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::_Hash<std::_Umap_traits<_Kty,int,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::emplace<std::pair<int,unsigned __int64>>(std::pair<int,unsigned __int64> &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Ty=std::pair<const int,int>,
              _Kty=int,
              _Hasher=std::hash<int>,
              _Keyeq=std::equal_to<int>,
              _Alloc=std::allocator<std::pair<const int,int>>
          ]
  c:\users\user\desktop\meshviewer\meshprocessing\mesh_segmenter.cpp(121): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::unordered_map<int,int,std::hash<int>,std::equal_to<_Kty>,std::allocator<_Ty>>::insert<std::pair<int,unsigned __int64>,void>(_Valty &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Ty=std::pair<const int,int>,
              _Kty=int,
              _Valty=std::pair<int,unsigned __int64>
          ]
  c:\users\user\desktop\meshviewer\meshprocessing\mesh_segmenter.cpp(121): note: 컴파일 중인 함수 템플릿 인스턴스화 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::unordered_map<int,int,std::hash<int>,std::equal_to<_Kty>,std::allocator<_Ty>>::insert<std::pair<int,unsigned __int64>,void>(_Valty &&)'에 대한 참조를 확인하십시오.
          with
          [
              _Ty=std::pair<const int,int>,
              _Kty=int,
              _Valty=std::pair<int,unsigned __int64>
          ]
  vec3.cpp
  vtkOFFReader.cxx
  vtk_widget.cpp
  코드를 생성하고 있습니다...
  qrc_mesh_processing.cpp
  MeshProcessing.vcxproj -> C:\Users\user\Desktop\MeshViewer\x64\Release\MeshProcessing.exe

**Comment by RoyKill** [comment]
How can I run this project?
